-- Creating and filling the 2018 Public Libraries Survey table

CREATE TABLE pls_fy2018_libraries (
    STABR VARCHAR(2) NOT NULL,
    FSCSKEY VARCHAR(6) PRIMARY KEY,
    LIBID VARCHAR(20) NOT NULL,
    LIBNAME VARCHAR(60) NOT NULL,
    ADDRESS VARCHAR(35) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    CNTY VARCHAR(20) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    C_RELATN VARCHAR(2) NOT NULL,
    C_LEGBAS VARCHAR(2) NOT NULL,
    C_ADMIN VARCHAR(2) NOT NULL,
    C_FSCS VARCHAR(1) NOT NULL,
    GEOCODE VARCHAR(3) NOT NULL,
    LSABOUND VARCHAR(1) NOT NULL,
    STARTDAT VARCHAR(10) NOT NULL,
    ENDDATE VARCHAR(10) NOT NULL,
    POPU_LSA INTEGER NOT NULL,
    POPU_UND INTEGER NOT NULL,
    CENTLIB INTEGER NOT NULL,
    BRANLIB INTEGER NOT NULL,
    BKMOB INTEGER NOT NULL,
    TOTSTAFF NUMERIC(9, 2) NOT NULL,
    BKVOL INTEGER NOT NULL,
    EBOOK INTEGER NOT NULL,
    AUDIO_PH INTEGER NOT NULL,
    AUDIO_DL INTEGER NOT NULL,
    VIDEO_PH INTEGER NOT NULL,
    VIDEO_DL INTEGER NOT NULL,
    EC_LO_OT INTEGER NOT NULL,
    SUBSCRIP INTEGER NOT NULL,
    HRS_OPEN INTEGER NOT NULL,
    VISITS INTEGER NOT NULL,
    REFERENC INTEGER NOT NULL,
    REGBOR INTEGER NOT NULL,
    TOTCIR INTEGER NOT NULL,
    KIDCIRCL INTEGER NOT NULL,
    TOTPRO INTEGER NOT NULL,
    GPTERMS INTEGER NOT NULL,
    PITUSR INTEGER NOT NULL,
    WIFISESS BIGINT NOT NULL,
    OBEREG VARCHAR(2) NOT NULL,
    STATSTRU VARCHAR(2) NOT NULL,
    STATNAME VARCHAR(2) NOT NULL,
    STATADDR VARCHAR(2) NOT NULL,
    LONGITUD NUMERIC(10, 7) NOT NULL,
    LATITUDE NUMERIC(9, 7) NOT NULL
);

COPY pls_fy2018_libraries
FROM 'C:\Users\jingn\Documents\SQL\sql_library_survey\pls_fy2018_libraries.csv'
WITH (FORMAT CSV, HEADER);

-- create index on the library column for faster query execution
CREATE INDEX libname_2018_idx ON pls_fy2018_libraries (libname);

-- check to see whether my importing process worked successfully
SELECT *
FROM pls_fy2018_libraries
LIMIT 5;


/* 2017
*/
-- import 2017 dataset
CREATE TABLE pls_fy2017_libraries (
    STABR VARCHAR(2) NOT NULL,
    FSCSKEY VARCHAR(6) PRIMARY KEY,
    LIBID VARCHAR(20) NOT NULL,
    LIBNAME VARCHAR(60) NOT NULL,
    ADDRESS VARCHAR(35) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    CNTY VARCHAR(20) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    C_RELATN VARCHAR(2) NOT NULL,
    C_LEGBAS VARCHAR(2) NOT NULL,
    C_ADMIN VARCHAR(2) NOT NULL,
    C_FSCS VARCHAR(1) NOT NULL,
    GEOCODE VARCHAR(3) NOT NULL,
    LSABOUND VARCHAR(1) NOT NULL,
    STARTDAT VARCHAR(10) NOT NULL,
    ENDDATE VARCHAR(10) NOT NULL,
    POPU_LSA INTEGER NOT NULL,
    POPU_UND INTEGER NOT NULL,
    CENTLIB INTEGER NOT NULL,
    BRANLIB INTEGER NOT NULL,
    BKMOB INTEGER NOT NULL,
    TOTSTAFF NUMERIC(9, 2) NOT NULL,
    BKVOL INTEGER NOT NULL,
    EBOOK INTEGER NOT NULL,
    AUDIO_PH INTEGER NOT NULL,
    AUDIO_DL INTEGER NOT NULL,
    VIDEO_PH INTEGER NOT NULL,
    VIDEO_DL INTEGER NOT NULL,
    EC_LO_OT INTEGER NOT NULL,
    SUBSCRIP INTEGER NOT NULL,
    HRS_OPEN INTEGER NOT NULL,
    VISITS INTEGER NOT NULL,
    REFERENC INTEGER NOT NULL,
    REGBOR INTEGER NOT NULL,
    TOTCIR INTEGER NOT NULL,
    KIDCIRCL INTEGER NOT NULL,
    TOTPRO INTEGER NOT NULL,
    GPTERMS INTEGER NOT NULL,
    PITUSR INTEGER NOT NULL,
    WIFISESS BIGINT NOT NULL,
    OBEREG VARCHAR(2) NOT NULL,
    STATSTRU VARCHAR(2) NOT NULL,
    STATNAME VARCHAR(2) NOT NULL,
    STATADDR VARCHAR(2) NOT NULL,
    LONGITUD NUMERIC(10, 7) NOT NULL,
    LATITUDE NUMERIC(9, 7) NOT NULL
);

COPY pls_fy2017_libraries
FROM 'C:\Users\jingn\Documents\SQL\sql_library_survey\pls_fy2017_libraries.csv'
WITH (FORMAT CSV, HEADER);

CREATE INDEX libname_2017_idx ON pls_fy2017_libraries (libname);

-- check to see whether my importing process worked successfully
SELECT *
FROM pls_fy2017_libraries
LIMIT 5;

/* 2016
*/
-- import 2016 dataset
-- do the same thing for 2017 dataset
CREATE TABLE pls_fy2016_libraries (
    STABR VARCHAR(2) NOT NULL,
    FSCSKEY VARCHAR(6) PRIMARY KEY,
    LIBID VARCHAR(20) NOT NULL,
    LIBNAME VARCHAR(60) NOT NULL,
    ADDRESS VARCHAR(35) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    CNTY VARCHAR(20) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    C_RELATN VARCHAR(2) NOT NULL,
    C_LEGBAS VARCHAR(2) NOT NULL,
    C_ADMIN VARCHAR(2) NOT NULL,
    C_FSCS VARCHAR(1) NOT NULL,
    GEOCODE VARCHAR(3) NOT NULL,
    LSABOUND VARCHAR(1) NOT NULL,
    STARTDAT VARCHAR(10) NOT NULL,
    ENDDATE VARCHAR(10) NOT NULL,
    POPU_LSA INTEGER NOT NULL,
    POPU_UND INTEGER NOT NULL,
    CENTLIB INTEGER NOT NULL,
    BRANLIB INTEGER NOT NULL,
    BKMOB INTEGER NOT NULL,
    TOTSTAFF NUMERIC(9, 2) NOT NULL,
    BKVOL INTEGER NOT NULL,
    EBOOK INTEGER NOT NULL,
    AUDIO_PH INTEGER NOT NULL,
    AUDIO_DL INTEGER NOT NULL,
    VIDEO_PH INTEGER NOT NULL,
    VIDEO_DL INTEGER NOT NULL,
    EC_LO_OT INTEGER NOT NULL,
    SUBSCRIP INTEGER NOT NULL,
    HRS_OPEN INTEGER NOT NULL,
    VISITS INTEGER NOT NULL,
    REFERENC INTEGER NOT NULL,
    REGBOR INTEGER NOT NULL,
    TOTCIR INTEGER NOT NULL,
    KIDCIRCL INTEGER NOT NULL,
    TOTPRO INTEGER NOT NULL,
    GPTERMS INTEGER NOT NULL,
    PITUSR INTEGER NOT NULL,
    WIFISESS BIGINT NOT NULL,
    OBEREG VARCHAR(2) NOT NULL,
    STATSTRU VARCHAR(2) NOT NULL,
    STATNAME VARCHAR(2) NOT NULL,
    STATADDR VARCHAR(2) NOT NULL,
    LONGITUD NUMERIC(10, 7) NOT NULL,
    LATITUDE NUMERIC(9, 7) NOT NULL
);

COPY pls_fy2016_libraries
FROM 'C:\Users\jingn\Documents\SQL\sql_library_survey\pls_fy2016_libraries.csv'
WITH (FORMAT CSV, HEADER);

CREATE INDEX libname_2016_idx ON pls_fy2016_libraries (libname);

-- check to see whether my importing process worked successfully
SELECT *
FROM pls_fy2016_libraries
LIMIT 5;

/* INVESTIGATE THE NUMBER OF VISITS
*/

-- add a year column to indicate the year of the data
ALTER TABLE pls_fy2018_libraries
ADD COLUMN year INT;
UPDATE pls_fy2018_libraries
SET year = 2018;


ALTER TABLE pls_fy2017_libraries
ADD COLUMN year INT;
UPDATE pls_fy2017_libraries
SET year = 2017;


ALTER TABLE pls_fy2016_libraries
ADD COLUMN year INT;
UPDATE pls_fy2016_libraries
SET year = 2016;


-- output: year, sum(visits)
-- select sum(visits)
-- union all 2018, 2017, 2016 data 
-- group by year
COPY (
SELECT 
    year,
    SUM(visits) AS total_visits
FROM (
    SELECT fscskey, visits, 2018 AS year
    FROM pls_fy2018_libraries
    WHERE visits >= 0

    UNION ALL

    SELECT fscskey, visits, 2017 AS year
    FROM pls_fy2017_libraries
    WHERE visits >= 0

    UNION ALL

    SELECT fscskey, visits, 2016 AS year
    FROM pls_fy2016_libraries
    WHERE visits >= 0
) AS combined
GROUP BY year
ORDER BY year DESC
) TO 'C:\Users\jingn\Documents\SQL\Library Survey\visit_count.txt'
WITH (FORMAT CSV, HEADER);


/* TRACK THE CHANGE IN VISITORS FOR EACH STATE
*/
SELECT 
	d18.stabr,
	SUM(d18.visits) visits_2018,
	SUM(d17.visits) visits_2017,
	SUM(d16.visits) visits_2016,
	round( ( SUM(d18.visits) - SUM(d17.visits))::numeric / SUM(d17.visits), 4) as visits_pct_change_1718,
	round( ( SUM(d17.visits) - SUM(d16.visits))::numeric / SUM(d16.visits), 4) as visits_pct_change_1617
FROM pls_fy2018_libraries d18
	JOIN pls_fy2017_libraries d17 ON d17.fscskey = d18.fscskey
	JOIN pls_fy2016_libraries d16 ON d16.fscskey = d18.fscskey
WHERE d18.visits >= 0 and d17.visits >= 0 and d16.visits >= 0
GROUP BY d18.stabr
ORDER BY d18.stabr;
